// Auto-generated by scripts/generate-endpoint-pages.mjs — do not edit manually
import type { ZudokuConfig } from "zudoku";

export const endpointNavigation: NonNullable<ZudokuConfig["navigation"]> = [
	{
		type: "category",
		label: "Overview",
		items: [
			{
				type: "doc",
				file: "introduction",
				label: "Getting Started",
				icon: "star",
			},
			{
				type: "doc",
				file: "webhooks",
				label: "Webhooks",
				icon: "webhook",
			},
			{
				type: "category",
				label: "Endpoints",
				icon: "layers",
				items: [
				{
					type: "category",
					label: "Identity Verification",
					icon: "id-card",
					link: "endpoints/overview/identity-verification",
					items: [
"endpoints/id-document",
"endpoints/face-match",
					],
				},
				{
					type: "category",
					label: "Compliance & Screening",
					icon: "shield-check",
					link: "endpoints/overview/compliance-screening",
					items: [
"endpoints/aml-screening",
"endpoints/business-aml-screening",
"endpoints/kyb-screening",
					],
				},
				{
					type: "category",
					label: "Address Verification",
					icon: "map-pin",
					link: "endpoints/overview/address-verification",
					items: [
"endpoints/address-verification",
					],
				},
				{
					type: "category",
					label: "Risk & Crypto",
					icon: "bitcoin",
					link: "endpoints/overview/risk-crypto",
					items: [
"endpoints/risk-assessment",
"endpoints/crypto-wallet-screening",
					],
				},
				{
					type: "category",
					label: "Government Registry Checks",
					icon: "landmark",
					link: "endpoints/overview/government-registry",
					items: [
						{
							type: "category",
							label: "🇿🇦 South Africa",
							link: "endpoints/overview/government-registry/south-africa",
							items: [
"endpoints/za-said-verification",
							],
						},
						{
							type: "category",
							label: "🇳🇬 Nigeria",
							link: "endpoints/overview/government-registry/nigeria",
							items: [
"endpoints/ng-bvn-verification",
"endpoints/ng-nin-verification",
"endpoints/ng-virtual-nin-verification",
"endpoints/ng-advanced-phone-number-verification",
"endpoints/ng-phone-number-lookup",
"endpoints/ng-cac-lookup",
"endpoints/ng-passport-verification",
							],
						},
						{
							type: "category",
							label: "🇬🇭 Ghana",
							link: "endpoints/overview/government-registry/ghana",
							items: [
"endpoints/gh-passport-lookup",
"endpoints/gh-voter-card-lookup",
"endpoints/gh-ssnit-lookup",
"endpoints/gh-drivers-license-lookup",
							],
						},
						{
							type: "category",
							label: "🇰🇪 Kenya",
							link: "endpoints/overview/government-registry/kenya",
							items: [
"endpoints/ke-passport-lookup",
"endpoints/ke-national-id-lookup",
"endpoints/ke-phone-number-lookup",
"endpoints/ke-tax-pin-verification",
							],
						},
					],
				},
				],
			},
		],
	},
	{
		type: "link",
		to: "/api",
		label: "API Reference",
	},
];
